#
# Copyright:: 2019, Chef Software, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'spec_helper'

describe RuboCop::Cop::Chef::DefinesChefSpecMatchers, :config do
  subject(:cop) { described_class.new(config) }

  it 'registers an offense when defining a ChefSpec matcher' do
    expect_offense(<<-RUBY)
      if defined?(ChefSpec)
      ^^^^^^^^^^^^^^^^^^^^^ ChefSpec matchers are now auto generated by ChefSpec 7.1+ and do not need to be defined in a cookbook
        def create_yum_repository(resource_name)
          ChefSpec::Matchers::ResourceMatcher.new(:yum_repository, :create, resource_name)
        end
      end
    RUBY
  end

  it "doesn't register an offense when checking if another method class is defined" do
    expect_no_offenses(<<-RUBY)
    if defined?(NotChefSpec)
      # something would go here right?
    end
    RUBY
  end
end
