require: rubocop-performance

# enable new cops for rubocop-performance
AllCops:
  NewCops: enable

Chef/Style/CommentFormat:
  Exclude:
    - 'lib/rubocop/cop/chef/comments_format.rb'

# this breaks cops with this error:
# undefined method `each_value' for #<RuboCop::AST::ArrayNode:0x00007fb285b2c7c8>
Style/HashEachMethods:
  Enabled: false

# Chef/Modernize/FoodcriticComments itself include an example Foocritic comment which alerts
Chef/Modernize/FoodcriticComments:
  Enabled: false

# reduces memory usage
Style/FrozenStringLiteralComment:
  Enabled: true

# makes it easier to read the matchers
Layout/HeredocIndentation:
  Enabled: true