# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-ws-notify

# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
rubygems:
  - cookstyle

artifact_channels:
  - dev
  - workstation-build
  - LTS-2024


release_branches:
  - workstation-LTS:
      version_constraint: 0.*
  - main:
      version_constraint: 7.*

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"

changelog:
  rollup_header: Changes not yet released to rubygems.org

pipelines:
  - habitat/build:
      env:
        - HAB_NONINTERACTIVE: "true"
        - HAB_NOCOLORING: "true"
        - HAB_STUDIO_SECRET_HAB_NONINTERACTIVE: "true"
  - habitat/test:
      description: Execute tests against the habitat artifact
      definition: .expeditor/habitat-test.pipeline.yml
      env:
        - HAB_NONINTERACTIVE: "true"
        - HAB_NOCOLORING: "true"
        - HAB_STUDIO_SECRET_HAB_NONINTERACTIVE: "true"
      trigger: pull_request

subscriptions:
  # These actions are taken, in order they are specified, anytime a Pull Request is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
      - bash:.expeditor/build_docs.sh
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Skip Changelog"
            - "Expeditor: Skip All"
      - trigger_pipeline:habitat/build:
          only_if: built_in:bump_version
          ignore_labels:
            - "Expeditor: Skip Habitat"
            - "Expeditor: Skip All"

    # the habitat chain
  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      # when all of the hab package publish to the unstable channel, test and promote them
      - trigger_pipeline:habitat/test
      - built_in:promote_habitat_packages

    # Subscribe to the promotion of the dev channel to acceptance
  - workload: project_promoted:{{agent_id}}:dev:*
    actions:
      - built_in:promote_habitat_packages
  - workload: project_promoted:{{agent_id}}:workstation-build:*
    actions:
      - built_in:promote_habitat_packages
