---
name: unit

'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-latest]
        ruby: ['3.1', '3.4']
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_WITHOUT: profiling debug docs
    name: Unit test on ${{ matrix.os }} with Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
